### PR TITLE
Feature/action annotation

### LINKED ISSUE #41: action annotation
This is a new syntax for extra metadata on a action, the syntax will be:
`@target_name(attr1=1, attr2='2')` .

When started design annotation, the syntax was:
`@annotation(target="xxx", attrs=[])`
which is not as expressive as the new syntax, I'm open to any feedbacks 🚧 .

----

An example.  
If an action `show_something` need authn, say the authn is handled by KGW, you can write a kuneiform file like this:
```
database test;

@kgw(authn='true')
action show_something() public {
    select * from something;
}
```
Really the attributes depends on the 'target' platform or system, in this case, KGW need an attribute named 'authn'.

---

NOTE:    
So far we've used:
- `#` for index name
- `$` for parameter name(in action declaration) and local variable(inside action)
- `@` for block_variable  inside the action declaration such as `select * from user where address=@caller;`

 But it still feels natural to use `@` for annotations.   

Two other options are:
- just use like `annotation()\n action()`,   which looks weird, the purpose of `annotation`  not clear 
- use another signs like `!` to mark annotation

### PR DESCRIPTION
**Pull request by Yaiba**
resolves #41 

on impl:
I tried to define two names in Parser:
- block_name: @ IDENTIFER, 
- annotaion_target:@ IDENTIFER

This seems reasonable, but it leads to confusing Parser in scenarios like `@action`, since `action` will be parser as keyword first, thus `@action` won't be reconginized as neither.

So I reuse the `@identifier` to represent both block_variable and annotation in Lexer.

Merge note:
need to merge kwilteam/kuneiform-grammar#14 first, then update submodule reference

---
update:  change parsed AST of annotation to string

### CODE REVIEW

**Comment by Yaiba** [comment]
kuneiform now output annotation as string.

**Comment by jchappelow** [comment]
Do you think there should be an "annotation parse" then or is that left to the use case impl like kgw?

**Comment by Yaiba** [comment]
> Do you think there should be an "annotation parser" then or is that left to the use case impl like kgw?

I think so, just in case our `syntax` changes and our downstream users will be affected. 🤔

**Comment by Yaiba** [comment]
> > Do you think there should be an "annotation parser" then or is that left to the use case impl like kgw?
> 
> I think so, just in case our `syntax` changes and our downstream users will be affected. 🤔

Maybe a parser is too heavy, just provide a util function instead?

**Comment by jchappelow** [comment]
> Maybe a parser is too heavy, just provide a util function instead?

Yeah, that sounds fine, just a function to go from string to structured annotation.

**Comment by Yaiba** [comment]
> > Maybe a parser is too heavy, just provide a util function instead?
> 
> Yeah, that sounds fine, just a function to go from string to structured annotation.

Added `ParseAnnotation` function for this, it's good enough I think

**Review by jchappelow — COMMENTED** [review]
Yeah, `ParseAnnotation` looks like a fine solution.  I think there might just be a [couple edges though](https://github.com/kwilteam/kuneiform/commit/8abdbb03d3124c69e1571ab75e96e3336fb2a5e9#r131956718), nothing big.  Maybe what we want in the regex is `([a-zA-Z0-9_]+)\s*=\s*(\d*\.\d+|\d+|'.*?')`?

Other minor thought is to put MustCompile at a package level variable.

**Comment by Yaiba** [comment]
> Yeah, `ParseAnnotation` looks like a fine solution. I think there might just be a [couple edges though](https://github.com/kwilteam/kuneiform/commit/8abdbb03d3124c69e1571ab75e96e3336fb2a5e9#r131956718), nothing big. Maybe what we want in the regex is `([a-zA-Z0-9_]+)\s*=\s*(\d*\.\d+|\d+|'.*?')`?
> 
> Other minor thought is to put MustCompile at a package level variable.



> Yeah, `ParseAnnotation` looks like a fine solution. I think there might just be a [couple edges though](https://github.com/kwilteam/kuneiform/commit/8abdbb03d3124c69e1571ab75e96e3336fb2a5e9#r131956718), nothing big. Maybe what we want in the regex is `([a-zA-Z0-9_]+)\s*=\s*(\d*\.\d+|\d+|'.*?')`?
> 
> Other minor thought is to put MustCompile at a package level variable.

yeah the float is actually not supported in Kuneiform.  Will move the MustCompile

**Review by jchappelow — APPROVED** [review]

**Review by jchappelow — APPROVED** [review]
LGTM!

**Pull request merged**
